#!/bin/bash
#
# ===----------------------------------------------------------------------===
#
#  Swift Android SDK: Top-level Build Script
#
# ===----------------------------------------------------------------------===

if [[ "$DOCKER" == "" ]]; then
    DOCKER=docker
fi

case $(arch) in
    arm64|aarch64)
        OS_ARCH_SUFFIX=-aarch64
        ;;
    amd64|x86_64)
        OS_ARCH_SUFFIX=
        ;;
    *)
        echo "Unknown architecture $(arch)"
        exit 1
        ;;
esac

case "${BUILD_VERSION}" in
    release)
        SWIFT_BRANCH="swift-6.1-branch"
        ;;
    devel)
        SWIFT_BRANCH="swift-6.2-branch"
        ;;
    trunk)
        SWIFT_BRANCH="development"
        ;;
    *)
        echo "Unknown build version: ${BUILD_VERSION}"
        exit 1
        ;;
esac

# Build the Docker image
$DOCKER build --build-arg OS_ARCH_SUFFIX=$OS_ARCH_SUFFIX --build-arg SWIFT_BRANCH=$SWIFT_BRANCH -t swift-android .

# Check-out the sources
scripts/fetch-source.sh --source-dir source

mkdir -p products

# Run the build
$DOCKER run -it --rm \
          -v ./source:/source \
          -v ./products:/products \
          swift-android \
          /scripts/build.sh --source-dir /source --products-dir /products
