#!/bin/bash -ex
#
# ===----------------------------------------------------------------------===
#
#  Swift Android SDK: Docker Container Build Script
#
# ===----------------------------------------------------------------------===

# default architectures to build for
TARGET_ARCHS=${TARGET_ARCHS:-aarch64,x86_64,armv7}

ANDROID_NDK_VERSION=android-ndk-r27c
ANDROID_API=28

if [[ "$DOCKER" == "" ]]; then
    DOCKER=docker
fi

case $(arch) in
    arm64|aarch64)
        OS_ARCH_SUFFIX=-aarch64
        ;;
    amd64|x86_64)
        OS_ARCH_SUFFIX=
        ;;
    *)
        echo "Unknown architecture $(arch)"
        exit 1
        ;;
esac

HOST_OS=ubuntu24.04
source ./scripts/toolchain-vars.sh

# Build the Docker image
$DOCKER build --build-arg OS_ARCH_SUFFIX=$OS_ARCH_SUFFIX --build-arg SWIFT_TOOLCHAIN_URL=$SWIFT_TOOLCHAIN_URL --build-arg ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION -t swift-android .

# Check-out and patch the sources
./scripts/fetch-source.sh --source-dir ${PWD}/source --swift-tag ${SWIFT_TAG}
./scripts/patch-sources.sh ${PWD}/source

mkdir -p products

echo "build-script-impl start ========="
ls -la $(find ${SDKROOT}/source -name build-script-impl)
cat $(find source -name build-script-impl)
echo "build-script-impl end  ========="
grep 'VALIDATING SYMBOLIC LINK' $(find ${SDKROOT}/source -name build-script-impl)


$DOCKER run -i --rm \
          -v ./source:/source \
          -v ./products:/products \
          swift-android \
          /scripts/build.sh \
            --source-dir /source \
            --products-dir /products \
            --host-toolchain /usr/local/swift \
            --android-api ${ANDROID_API} \
            --ndk-home /usr/local/ndk/${ANDROID_NDK_VERSION} \
            --archs ${TARGET_ARCHS}
