#!/bin/bash -ex
#
# ===----------------------------------------------------------------------===
#
#  Swift Android SDK: Docker Container Build Script
#
# ===----------------------------------------------------------------------===

if [[ "$DOCKER" == "" ]]; then
    DOCKER=docker
fi

case $(arch) in
    arm64|aarch64)
        OS_ARCH_SUFFIX=-aarch64
        ;;
    amd64|x86_64)
        OS_ARCH_SUFFIX=
        ;;
    *)
        echo "Unknown architecture $(arch)"
        exit 1
        ;;
esac

HOST_OS=ubuntu24.04
source ./scripts/toolchain-vars.sh

ANDROID_API=28
ANDROID_NDK_VERSION=android-ndk-r27c

# Build the Docker image
$DOCKER build --build-arg OS_ARCH_SUFFIX=$OS_ARCH_SUFFIX --build-arg SWIFT_TOOLCHAIN_URL=$SWIFT_TOOLCHAIN_URL --build-arg ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION -t swift-android .

echo "Testing docker container"
$DOCKER run -it --rm \
          -v ./source:/source \
          -v ./products:/products \
          swift-android \
          echo "Docker Test"
echo "Done testing docker container"

# Check-out the sources
scripts/fetch-source.sh --source-dir source --swift-tag ${SWIFT_TAG}

mkdir -p products

# Run the build
$DOCKER run -it --rm \
          -v ./source:/source \
          -v ./products:/products \
          swift-android \
          /scripts/build.sh --source-dir /source --products-dir /products --android-api ${ANDROID_API} --host-toolchain /usr/local/swift --archs ${TARGET_ARCHS}
