name: Build Docker images
on: [pull_request]

env:
  ghprbPullId: ${{ github.event.number }}
  ghprbGhRepository: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
   build:
     name: Build Docker images
     runs-on: ubuntu-latest
     if: false
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker images
        run: ./ci_test.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-logs
          path: |
            *.log

   static-linux-build:
     name: Build Static Linux image
     runs-on: ubuntu-latest
     if: false
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker images
        working-directory: swift-ci/sdks/static-linux
        run: ./build

   android-build:
     name: Build Android ${{ matrix.arch }} SDK
     strategy:
       fail-fast: false
       matrix:
         arch: [armv7,aarch64,x86_64]
     #name: Build Android SDK
     runs-on: ubuntu-24.04
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Android SDK
        working-directory: swift-ci/sdks/android
        run: |
          sudo apt install ninja-build
          TARGET_ARCHS=${{ matrix.arch }} ./build
          #./build

